### PR TITLE
unify base boxes

### PR DESCRIPTION
**Pull request by zxaos**
See #308

### CODE REVIEW

**Comment by philipnorton42** [comment]
I like the changes here, but I'm guessing this will also create some backward compatibility issues?

**Comment by zxaos** [comment]
Yep, since it's moving everyone to bento/ base boxes instead of the various ones they're on now, VMs should be destroyed, vlad updated, then VMs recreated.

**Comment by zxaos** [comment]
But at the same time, if backwards compatibility is going to be interrupted with #312 it might be good to put this with it so it's only interrupted once?

**Comment by danbohea** [comment]
Yep, I'm all for this. And like @zxaos says, if we've already merged stuff that's gonna effect existing installations then we might as well sneak a few more in. I'd love to get the current drush branch merged into the next release but can't currently test it fully due to CentOS not provisioning.

**Pull request merged**
