### PR TITLE
Mbarcia win81 ubuntu1404

### PR DESCRIPTION
**Pull request by mbarcia**
I've been using the Trusty VM built by this code for a few weeks now, as a 2nd. workstation, running in my Windows laptop, and I'm very happy with it. 

This is a separate new branch, with a broader compatibility (Trusty is supported in the guest in addition to Precise, and Windows is supported on the host, in addition to Linux and OSX).

I've seen the dev branch got some major updates, many of which pursuing the same functionality achieved here (ie. xhprof). I hope to sync the dev branch with this one as soon as I can.

Feel free to take a look at it (ie. the PHP versions) hope this helps.

### CODE REVIEW

**Comment by philipnorton42** [comment]
Hi @mbarcia,
Thanks for this, there is some really great changes here but I'm afraid I can't merge this into Vlad as a single commit. It breaks a lot of stuff I've spent the last few weeks tweaking and changing to fix bugs and the like. What I'll do is read through your changes and pull them in individually. I'll also try to attribute the changes to you correctly.
As an aside, would it be possible to get your Windows support changes as a single pull request? That would be amazing!
Phil

**Comment by mbarcia** [comment]
Hello philip, sorry for the delay reacting to this. Please, which branch or tag should I use as a starting point? Thank you.

**Comment by danbohea** [comment]
There's a lot of activity slated for the forthcoming 1.1 tag over the next month. I'd advise starting from the current dev branch. I'd also keep one eye on what's happening in dev and merge in changes as they happen if you can.

Bad timing really but there's a fair amount of activity around the Vagrantfile at the moment: an un-merged PR (#161) and a branch that looks to add support for using custom base boxes (#156) - these will likely lead to some fun merge conflicts :) I'll try to make sure that this issue is updated with news of anything that could be relevant in order to give you a heads up.

@philipnorton42 We're gonna need to mindful about what order we merge all this stuff in.

**Comment by danbohea** [comment]
Also - let's try to keep this conversation over at #75 if we can. That issue is still open and people have eyes on it.

**Comment by mbarcia** [comment]
Hi Dan, thanks for the advice. I will give this a shot, aiming to contribute the PR today, and let you know.

**Pull request closed without merging**
