### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ChandeepKhosa**
Added dependencies section to make it easier to get VLAD installed

### CODE REVIEW

**Comment by philipnorton42** [comment]
Thanks for this Chandeep. Sensible suggestions. Could I ask you to submit the pull request against the dev branch instead though? It really helps me out when releasing new versions ;)

**Comment by ChandeepKhosa** [comment]
defnitely, will do


Kind regards,

Chandeep Singh Khosa | Director / Drupal Developer

Imagine Creativity : Web Development, Digital Marketing & Training

Linked In // Twitter // Website // 07962 382 442 // skype = imagine.c

**Comment by danbohea** [comment]
VMware & Parallels are possible alternatives to VirtualBox too - any mention of deps should probably reflect this.

**Comment by philipnorton42** [comment]
Good point @danbohea I always forget about non-virtual box systems :(

**Pull request closed without merging**
