### PR TITLE
Windows version

### PR DESCRIPTION
**Pull request by mbarcia**
#75 pull request

### CODE REVIEW

**Comment by philipnorton42** [comment]
Hi @mbarcia! Thanks for turning this around, really appreciate what you've done here :)

I have created a branch called 'windows' and merged your changes into it. This will allow other people to test things out, as I don't really have any way to test this. What I will do is review things as they are and see if there is anything I can alter in terms of best practice.

**Comment by mbarcia** [comment]
Hi Philip, you're welcome. It's been since Amsterdam that I wanted to contribute this so I'm glad I finally found the time and you liked it.

The way the patch is written (especifically, the addition of wrapping ifs in Vagrantfile) makes it difficult for the new windows branch to keep it up with dev, as any small change in Vagrantfile breaks the "if structures", causing a merge conflicts. 

For example, I just wanted to contribute a fix to #168 with a PR and found the latest commit (df6ca624aaaaab1d1dcf03da12d1a5ad0ae9e42b) introduced a merge conflict.

So, prove me wrong, I think it won't be easy to maintain 2 long-term branches (dev and windows). I believe Windows support is a VLAD feature, or it is not. If it is, then it should be properly incorporated to dev (and master eventually), and should have support from the VLAD team and contributors.

The fact that nor you neither Dan can test on Windows is an understandable concern, but I'd say: if you break windows, nevermind! I'll fix it  :-) It will always be less work than attempting to keep branches in sync.

And BTW, installing Ansible in the guest (approach taken by this PR) maybe a good option in OSX as well. Benefits would be:
* one less piece of software to install in the host
* same version of ansible accross all VLAD installations

My 2 cents, cheers

**Comment by philipnorton42** [comment]
Thanks Mariano. My intention was to review the windows branch this weekend and then merge it in when possible. Life, as it happens, gets in the way from time to time. Thanks for the heads up on the merge conflicts, I'll try and get it done this week. I do have access to certain Windows environments so I'm not completely lost here. But your offer to tackle the Windows features is certainly welcome! :)

Installing Ansible on the guest box seems like an interesting idea. I'm going to suggest we keep Ansible as it is currently, just because everything is geared around a local install. I will keep it in mind though.

Anyhow, I'm going to close this pull request now as it has served it's purpose. I'll try and keep you posted on this being merged into dev.

**Comment by mbarcia** [comment]
Hi Philip, no prob. and this is great news. Would it be of help if I fix the conflict and re-roll the PR against the de branch? Also, I would be adding comments to the patch in order to provide a better insight about how windows is supported. Please let me know, cheers.

**Comment by philipnorton42** [comment]
Hi @mbarcia. Not a problem. I've already done the merge conflict so things are up to date again. Adding comments to the pull request might be handy actually, if you have a spare few minutes I would love that :+1: 

I have also managed to get a Windows machine at work so I will be testing this branch this week. Hopefully we can merge it in by Friday :)

**Comment by philipnorton42** [comment]
Ok, so after playing with the Windows version of Vagrant for a bit I can safely say that Windows is a massive pile of ass and I am hugely happy that I don't have to use it anymore. How anyone can get anything done on that system is beyond me.

I'm not sure if it's Vlad or something else but I cant even get Vagrant to boot the box correctly. I assume that things worked correctly on your end.

I had started making some notes for the documentation site, but haven't got any further than this:


Run the command prompt in administration mode when using Vagrant.

Ensure that the Vagrant home directory does not have a space in it. To do this run the following command within an administration command prompt.

    setx VAGRANT_HOME "c:\vagrant\home\path" /M

**Comment by danbohea** [comment]
Rather you than me!

**Comment by philipnorton42** [comment]
hehehe! 

Actually, I think the issue might be a better place to discuss this, so I'm going to move this discussion there :)

(this is a closed pull request after all)

**Pull request closed without merging**
