### PR TITLE
Adding conditional imports and apache/mysql defaults

### PR DESCRIPTION
**Pull request by mbarcia**
Ansible's [conditional imports](https://docs.ansible.com/playbooks_conditionals.html#conditional-imports) can load vars_files based upon ansible facts (ansible_*). This allows us to set values according to OS family and distribution/release.

This PR loads vars_files according OS family and distribution, and adds defaults for apache and mysql.

This useful technique can be used in other places where repetition of code between Debian and RedHat can be mitigated. It's a pity that, at the moment, it cannot be used in roles but only in playbooks.

### CODE REVIEW

**Comment by mbarcia** [comment]
Tracking issue is  #196

**Comment by philipnorton42** [comment]
I can see what you are doing here, but I think a slight alteration might be in order.

Essentially, we want to avoid adding role based variables into the main system itself. So variables like apache2_docroot and mysql_service_name would be defined in the role itself.

I see your note about conditional imports not being available in roles, which is a shame, but as we only officially support Redhat or Debian then I think using ansible_os_family to include one file or the other from the default/main.yml file (like the following) is probably enough:

   - include: var_{{ ansible_os_family }}.yml

What do you think? I think your use of variables in the roles themselves is great, but some tweaking needed :).

**Comment by mbarcia** [comment]
Hello Philip,

Thanks for the feedback. It seems I was being misleaded by a very old comment somewhere. But effectively, the confusion comes because vars_files is not up for the task, but *include_vars* is.

[include_vars](http://docs.ansible.com/include_vars_module.html) is the solution (introduced in Ansible 1.4).

So, I've completed the switch to include_vars in 70187fc (after you `placed the comment). 

vars_files would still be needed for storing a few global variables that not be part of any particular role. Sounds good? Cheers,

**Comment by philipnorton42** [comment]
Ok, I'm going to close this pull request, but only because of my points above. The variables for a role should be contained within the role, rather than in the main Vlad settings files.

**Pull request closed without merging**
