### PR TITLE
make vagrant store its directory next to the vlad settings file

### PR DESCRIPTION
**Pull request by zxaos**
Automatically change the location that Vagrant places the `.vagrant` directory. Supports a scenario where  vlad is installed via a package manager (see #253 ).

### CODE REVIEW

**Comment by zxaos** [comment]
@philipnorton42 I think this might potentially need the notice-required flag? (or on #253, then?) If someone updates vlad over an existing configuration, this update will make them need to re-create the VM and so they might want to make sure everything's exported from the old one first.

**Comment by philipnorton42** [comment]
That's very true actually. We do have a notice blog, but we can create some other warnings to let people know.

**Comment by danbohea** [comment]
I think @zxaos means the "notice required" issue label to remind us to mention this on the notice board when we next tag a release (now added).

**Comment by zxaos** [comment]
@danbohea yes, that :+1:

**Comment by wizonesolutions** [comment]
Hmm...is it possible to check for the existence of a `.vagrant` directory in the Vlad root and output a warning if it's found, telling the user how to fix it?

It super threw me off, and now I know how to fix it (thanks @zxaos), but I had _no clue_ what was going on and wound up rebuilding the machine in question (since I was going to reload the DB anyway).

**Pull request merged**
