### PR TITLE
support local setings overrides

### PR DESCRIPTION
**Pull request by zxaos**
Implements #161

Of course, it does it in a general way that doesn't limit which variables can be overridden, so that might be either useful or dangerous.

This time, minus debug code

### CODE REVIEW

**Comment by danbohea** [comment]
Thanks for this. My initial feedback:

You'll need to make sure that the settings are also loaded in site_custom.yml (not just site.yml) - ideally in between the regular settings and the custom settings. This way any custom role will be aware of anything set in vlad_local_settings.yml.

Vagrantfile:

Your Ruby seems much better than mine (not hard!), I like the look of the iterative loading stuff around line 40 of the :)

That said, especially given how Ruby is a little foreign to me and others with eyes on this code, would you mind adding in some further comments? I'd like to think I could come back to this and get what's going on in a few seconds rather than a minute or so - good comments would certainly help with that. Also, along the same lines I guess, any chance we can avoid the single character variables? In the loop  I'm guessing `f` is file but the others still aren't clear to me (reading up points to `k` = constant and `v` = vector but I could be wrong) - I'd rather see all of them as at least one word to make everything more readable and quicker (for a human that isn't the author) to interpret.

Minor amends I reckon - I'm generally liking the look of this and am keen to give it a go :) Cheers!

**Comment by zxaos** [comment]
Thanks, I'lll update the branch shortly.

I haven't tried out the custom role yet - but won't it cause problems to load the local overrides before the custom role? The custom role could still set project-level variables and leave the user with no way to override them on their development machine.

I'll push a commit with them in the order you listed, but thought I should ask.

I've added some comments and renamed the iterators. ```|k,v|``` is just like using ```i``` in a for loop typically, but for iterating over key/value pairs at the same time.

Also fixed an issue where the output would list every file as a local override (oops) and cleaned up the output a bit.

**Comment by danbohea** [comment]
Key & Value! I should have guessed that - it was late (that's my excuse). Thanks for clearing that up.

> I haven't tried out the custom role yet - but won't it cause problems to load the local overrides before the custom role? The custom role could still set project-level variables and leave the user with no way to override them on their development machine.

That's a very good point, but you could also chalk that up as just a badly thought out custom role. I guess that ultimately it's down to the user to properly understand the reason for each settings file - there's potential for shooting yourself in the foot either way around. Let's go with your suggestion of local settings being loaded last and see how it pans out - you're probably right here, I'm a little manic right this second :)

**Comment by zxaos** [comment]
Ok, the order is swapped now.

Not sure the best way to discourage foot-shooting in this situation. Maybe don't provide a ```local_settings``` example file (to discourage unnecessary use) but mention it in the docs somewhere?

**Comment by danbohea** [comment]
Just tested this and it seems to work well :)

I agree that there's no need to provide an example local settings file and that we should just update the docs to cover this functionality (will look at this next).

Cheers!

**Pull request merged**
